### ISSUE TITLE
お絵かきの永続化

### ISSUE THREAD

**Issue by kageryosan** [epw-dev/twi-oekaki#4]

**Comment by taqm** [comment]
完全に永続化する必要はなくて、
途中から参加した人が中途半端な絵になるのを防ぐ程度で良さそう（揮発性のあるメモリキャッシュくらい）

サーバの冗長化とかする時に細かいことは考える

**Comment by taqm** [comment]
画面をリロード時に状態を復元できるようになった
が、パフォーマンスに問題が出てきたので別Issueにて対応 #12
